Repository openshift/library, pull requests merged in 2018-04, with the labels that each got.

#72 Add EAP CD to OpenShift official.yaml
  official.yaml
  official/README.md
  official/eap-cd/imagestreams/eap-cd-openshift-rhel7.json
  official/eap-cd/templates/eap-cd-amq-persistent-s2i.json
  official/eap-cd/templates/eap-cd-basic-s2i.json
  official/eap-cd/templates/eap-cd-postgresql-persistent-s2i.json
  official/eap-cd/templates/eap-cd-tx-recovery-s2i.json
  official/index.json
Labels: size/XXL

#80 add rhoar nodejs imagestream
  community.yaml
  community/README.md
  community/index.json
  official.yaml
  official/README.md
  official/cakephp/templates/cakephp-example.json
  official/cakephp/templates/cakephp-mysql-example.json
  official/cakephp/templates/cakephp-mysql-persistent.json
  official/index.json
  official/nodejs/imagestreams/rhoar-nodejs-rhel7.json
Labels: size/L

#83 [CLOUD-2516] Updating with JDV 6.4 image information
  official.yaml
  official/README.md
  official/datavirt/imagestreams/jboss-datavirt63-driver-openshift-rhel7.json
  official/datavirt/imagestreams/jboss-datavirt63-openshift-rhel7.json
  official/datavirt/imagestreams/jboss-datavirt64-driver-openshift-rhel7.json
  official/datavirt/imagestreams/jboss-datavirt64-openshift-rhel7.json
  official/datavirt/templates/datavirt64-basic-s2i.json
  official/datavirt/templates/datavirt64-extensions-support-s2i.json
  official/datavirt/templates/datavirt64-secure-s2i.json
  official/index.json
Labels: size/XL

#85 Updating with merged nodejs imagestream with RHOAR from RHSCL
  official.yaml
  official/README.md
  official/index.json
  official/nodejs/imagestreams/nodejs-rhel7.json
  official/nodejs/templates/nodejs-example.json
  official/nodejs/templates/nodejs-mongo-persistent.json
  official/nodejs/templates/nodejs-mongodb-example.json
Labels: size/M
