Repository openshift/library, pull requests merged in 2018-09, with the labels that each got.

#110 EAP / EAP CD template updates
  official.yaml
  official/README.md
  official/eap/imagestreams/jboss-eap64-openshift-rhel7.json
  official/eap/imagestreams/jboss-eap70-openshift-rhel7.json
  official/eap/imagestreams/jboss-eap71-openshift-rhel7.json
  official/eap/templates/eap64-amq-persistent-s2i.json
  official/eap/templates/eap64-amq-s2i.json
  official/eap/templates/eap64-basic-s2i.json
  official/eap/templates/eap64-https-s2i.json
  official/eap/templates/eap64-mongodb-persistent-s2i.json
  official/eap/templates/eap64-mongodb-s2i.json
  official/eap/templates/eap64-mysql-persistent-s2i.json
  official/eap/templates/eap64-mysql-s2i.json
  official/eap/templates/eap64-postgresql-persistent-s2i.json
  official/eap/templates/eap64-postgresql-s2i.json
  official/eap/templates/eap64-sso-s2i.json
  official/eap/templates/eap64-third-party-db-s2i.json
  official/eap/templates/eap64-tx-recovery-s2i.json
  official/eap/templates/eap71-amq-persistent-s2i.json
  official/eap/templates/eap71-amq-s2i.json
  official/eap/templates/eap71-basic-s2i.json
  official/eap/templates/eap71-https-s2i.json
  official/eap/templates/eap71-mongodb-persistent-s2i.json
  official/eap/templates/eap71-mongodb-s2i.json
  official/eap/templates/eap71-mysql-persistent-s2i.json
  official/eap/templates/eap71-mysql-s2i.json
  official/eap/templates/eap71-postgresql-persistent-s2i.json
  official/eap/templates/eap71-postgresql-s2i.json
  official/eap/templates/eap71-sso-s2i.json
  official/eap/templates/eap71-third-party-db-s2i.json
  official/eap/templates/eap71-tx-recovery-s2i.json
  official/index.json
Labels: needs-ok-to-test, size/L

#111 Update Fuse entries with 7.1 release
  official.yaml
Labels: needs-ok-to-test, size/XS

#113 Bump webserver_version to 1.4.16; change to registry.redhat.io
  official.yaml
  official/README.md
  official/index.json
  official/webserver/imagestreams/jboss-webserver30-tomcat7-openshift-rhel7.json
  official/webserver/imagestreams/jboss-webserver30-tomcat8-openshift-rhel7.json
  official/webserver/imagestreams/jboss-webserver31-tomcat7-openshift-rhel7.json
  official/webserver/imagestreams/jboss-webserver31-tomcat8-openshift-rhel7.json
  official/webserver/templates/jws31-tomcat7-basic-s2i.json
  official/webserver/templates/jws31-tomcat7-https-s2i.json
  official/webserver/templates/jws31-tomcat7-mongodb-persistent-s2i.json
  official/webserver/templates/jws31-tomcat7-mongodb-s2i.json
  official/webserver/templates/jws31-tomcat7-mysql-persistent-s2i.json
  official/webserver/templates/jws31-tomcat7-mysql-s2i.json
  official/webserver/templates/jws31-tomcat7-postgresql-persistent-s2i.json
  official/webserver/templates/jws31-tomcat7-postgresql-s2i.json
  official/webserver/templates/jws31-tomcat8-basic-s2i.json
  official/webserver/templates/jws31-tomcat8-https-s2i.json
  official/webserver/templates/jws31-tomcat8-mongodb-persistent-s2i.json
  official/webserver/templates/jws31-tomcat8-mongodb-s2i.json
  official/webserver/templates/jws31-tomcat8-mysql-persistent-s2i.json
  official/webserver/templates/jws31-tomcat8-mysql-s2i.json
  official/webserver/templates/jws31-tomcat8-postgresql-persistent-s2i.json
  official/webserver/templates/jws31-tomcat8-postgresql-s2i.json
Labels: lgtm, size/L

#115 add owners file
  OWNERS
Labels: size/XS

#117 Update EAP imagestreams / templates to latest version for registry switch
  official.yaml
  official/README.md
  official/eap/imagestreams/jboss-eap64-openshift-rhel7.json
  official/eap/imagestreams/jboss-eap70-openshift-rhel7.json
  official/eap/imagestreams/jboss-eap71-openshift-rhel7.json
  official/eap/templates/eap64-amq-persistent-s2i.json
  official/eap/templates/eap64-amq-s2i.json
  official/eap/templates/eap64-basic-s2i.json
  official/eap/templates/eap64-https-s2i.json
  official/eap/templates/eap64-mongodb-persistent-s2i.json
  official/eap/templates/eap64-mongodb-s2i.json
  official/eap/templates/eap64-mysql-persistent-s2i.json
  official/eap/templates/eap64-mysql-s2i.json
  official/eap/templates/eap64-postgresql-persistent-s2i.json
  official/eap/templates/eap64-postgresql-s2i.json
  official/eap/templates/eap64-sso-s2i.json
  official/eap/templates/eap64-third-party-db-s2i.json
  official/eap/templates/eap64-tx-recovery-s2i.json
  official/eap/templates/eap71-amq-persistent-s2i.json
  official/eap/templates/eap71-amq-s2i.json
  official/eap/templates/eap71-basic-s2i.json
  official/eap/templates/eap71-https-s2i.json
  official/eap/templates/eap71-mongodb-persistent-s2i.json
  official/eap/templates/eap71-mongodb-s2i.json
  official/eap/templates/eap71-mysql-persistent-s2i.json
  official/eap/templates/eap71-mysql-s2i.json
  official/eap/templates/eap71-postgresql-persistent-s2i.json
  official/eap/templates/eap71-postgresql-s2i.json
  official/eap/templates/eap71-sso-s2i.json
  official/eap/templates/eap71-third-party-db-s2i.json
  official/eap/templates/eap71-tx-recovery-s2i.json
  official/index.json
Labels: approved, lgtm, size/XL

#123 Update Data Grid image streams/templates for registry switch
  official.yaml
  official/README.md
  official/datagrid/imagestreams/jboss-datagrid65-client-openshift-rhel7.json
  official/datagrid/imagestreams/jboss-datagrid65-openshift-rhel7.json
  official/datagrid/imagestreams/jboss-datagrid71-client-openshift-rhel7.json
  official/datagrid/imagestreams/jboss-datagrid71-openshift-rhel7.json
  official/datagrid/imagestreams/jboss-datagrid72-openshift-rhel7.json
  official/datagrid/templates/datagrid71-basic.json
  official/datagrid/templates/datagrid71-https.json
  official/datagrid/templates/datagrid71-mysql-persistent.json
  official/datagrid/templates/datagrid71-mysql.json
  official/datagrid/templates/datagrid71-postgresql-persistent.json
  official/datagrid/templates/datagrid71-postgresql.json
  official/index.json
Labels: approved, lgtm, size/L

#126 add dv v6.3 imagestreamtags, remove v1.3 content
  official.yaml
  official/README.md
  official/datavirt/imagestreams/jboss-datavirt64-driver-openshift-rhel7.json
  official/datavirt/imagestreams/jboss-datavirt64-openshift-rhel7.json
  official/index.json
Labels: approved, lgtm, size/L

#119 update official.yaml for library/ansible reconciliation; ran import t…
  official.yaml
Labels: approved, lgtm, size/L

#127 Update EAP CD streams and templates to point to CD13-OS tag
  community/perl/imagestreams/perl-centos7.json
  official.yaml
  official/README.md
  official/cakephp/templates/cakephp-example.json
  official/cakephp/templates/cakephp-mysql-example.json
  official/cakephp/templates/cakephp-mysql-persistent.json
  official/dancer/templates/dancer-example.json
  official/dancer/templates/dancer-mysql-example.json
  official/dancer/templates/dancer-mysql-persistent.json
  official/django/templates/django-example.json
  official/django/templates/django-psql-example.json
  official/django/templates/django-psql-persistent.json
  official/index.json
  official/jenkins/templates/jenkins-ephemeral.json
  official/jenkins/templates/jenkins-persistent.json
  official/mariadb/templates/mariadb-ephemeral.json
  official/mariadb/templates/mariadb-persistent.json
  official/mongodb/templates/mongodb-ephemeral.json
  official/mongodb/templates/mongodb-persistent.json
  official/nodejs/templates/nodejs-mongo-persistent.json
  official/nodejs/templates/nodejs-mongodb-example.json
  official/perl/imagestreams/perl-rhel7.json
  official/postgresql/templates/postgresql-ephemeral.json
  official/postgresql/templates/postgresql-persistent.json
  official/rails/templates/rails-pgsql-persistent.json
  official/rails/templates/rails-postgresql-example.json
Labels: approved, lgtm, size/L
