Repository openshift/library, pull requests merged in 2018-07, with the labels that each got.

#94 [RHPAM-859] - Include RHPAM templates in OpenShift release
  official.yaml
  official/README.md
  official/index.json
  official/rhpam/imagestreams/rhpam70-businesscentral-openshift-rhel7.json
  official/rhpam/imagestreams/rhpam70-kieserver-openshift-rhel7.json
  official/rhpam/templates/rhpam70-authoring.json
  official/rhpam/templates/rhpam70-kieserver-mysql.json
  official/rhpam/templates/rhpam70-kieserver-postgresql.json
  official/rhpam/templates/rhpam70-prod-immutable-kieserver.json
Labels: size/XXL

#98 allow for arch specific tags
  import_content.py
Labels: size/S

#99 Update EAP CD ImageStream and templates to 13.0
  official.yaml
  official/README.md
  official/eap-cd/imagestreams/eap-cd-openshift-rhel7.json
  official/eap-cd/templates/eap-cd-amq-persistent-s2i.json
  official/eap-cd/templates/eap-cd-basic-s2i.json
  official/eap-cd/templates/eap-cd-postgresql-persistent-s2i.json
  official/index.json
Labels: size/L

#100 Add Fuse entries to Online starter plan
  official.yaml
Labels: size/XS

#101 [RHDM-662] - Update RHDM templates on OCP and OSO
  official.yaml
  official/README.md
  official/index.json
  official/rhdm/imagestreams/rhdm70-decisioncentral-openshift-rhel7.json
  official/rhdm/imagestreams/rhdm70-kieserver-openshift-rhel7.json
  official/rhdm/templates/rhdm70-full-persistent.json
  official/rhdm/templates/rhdm70-kieserver-basic-s2i.json
  official/rhdm/templates/rhdm70-kieserver-https-s2i.json
  official/rhdm/templates/rhdm70-kieserver.json
Labels: size/XL

#103 CLOUD-2699 - Remove EAP 7.0 templates, update EAP templates to latest release
  official.yaml
  official/README.md
  official/eap/imagestreams/jboss-eap64-openshift-rhel7.json
  official/eap/imagestreams/jboss-eap70-openshift-rhel7.json
  official/eap/imagestreams/jboss-eap71-openshift-rhel7.json
  official/eap/templates/eap64-amq-persistent-s2i.json
  official/eap/templates/eap64-amq-s2i.json
  official/eap/templates/eap64-basic-s2i.json
  official/eap/templates/eap64-https-s2i.json
  official/eap/templates/eap64-mongodb-persistent-s2i.json
  official/eap/templates/eap64-mongodb-s2i.json
  official/eap/templates/eap64-mysql-persistent-s2i.json
  official/eap/templates/eap64-mysql-s2i.json
  official/eap/templates/eap64-postgresql-persistent-s2i.json
  official/eap/templates/eap64-postgresql-s2i.json
  official/eap/templates/eap64-sso-s2i.json
  official/eap/templates/eap64-third-party-db-s2i.json
  official/eap/templates/eap64-tx-recovery-s2i.json
  official/eap/templates/eap70-amq-persistent-s2i.json
  official/eap/templates/eap70-amq-s2i.json
  official/eap/templates/eap70-basic-s2i.json
  official/eap/templates/eap70-https-s2i.json
  official/eap/templates/eap70-mongodb-persistent-s2i.json
  official/eap/templates/eap70-mongodb-s2i.json
  official/eap/templates/eap70-mysql-persistent-s2i.json
  official/eap/templates/eap70-mysql-s2i.json
  official/eap/templates/eap70-postgresql-persistent-s2i.json
  official/eap/templates/eap70-postgresql-s2i.json
  official/eap/templates/eap70-sso-s2i.json
  official/eap/templates/eap70-third-party-db-s2i.json
  official/eap/templates/eap70-tx-recovery-s2i.json
  official/eap/templates/eap71-amq-persistent-s2i.json
  official/eap/templates/eap71-amq-s2i.json
  official/eap/templates/eap71-basic-s2i.json
  official/eap/templates/eap71-https-s2i.json
  official/eap/templates/eap71-mongodb-persistent-s2i.json
  official/eap/templates/eap71-mongodb-s2i.json
  official/eap/templates/eap71-mysql-persistent-s2i.json
  official/eap/templates/eap71-mysql-s2i.json
  official/eap/templates/eap71-postgresql-persistent-s2i.json
  official/eap/templates/eap71-postgresql-s2i.json
  official/eap/templates/eap71-sso-s2i.json
  official/eap/templates/eap71-third-party-db-s2i.json
  official/eap/templates/eap71-tx-recovery-s2i.json
  official/fis/imagestreams/fis-java-openshift-rhel7.json
  official/fis/imagestreams/fis-karaf-openshift-rhel7.json
  official/index.json
Labels: size/XXL

#104 [KEYCLOAK-7750] Update RH-SSO image streams and templates to RH-SSO 7.2.3.GA version (xpaas 'ose-v1.4.14' tag)
  official.yaml
  official/README.md
  official/index.json
  official/sso/imagestreams/redhat-sso70-openshift-rhel7.json
  official/sso/imagestreams/redhat-sso71-openshift-rhel7.json
  official/sso/imagestreams/redhat-sso72-openshift-rhel7.json
  official/sso/templates/sso72-https.json
  official/sso/templates/sso72-mysql-persistent.json
  official/sso/templates/sso72-mysql.json
  official/sso/templates/sso72-postgresql-persistent.json
  official/sso/templates/sso72-postgresql.json
  official/sso/templates/sso72-x509-https.json
Labels: size/L
