Repository openshift/library, pull requests merged in 2018-11, with the labels that each got.

#136 remove broken infinispan content
  community.yaml
Labels: approved, size/S

#138 Use nodeshift for upstream community Node.js
  community.yaml
  community/README.md
  community/index.json
  community/nodejs/imagestreams/nodejs-centos7.json
Labels: approved, lgtm, size/M

#137 Update Infinispan templates
  community.yaml
  community/README.md
  community/index.json
  community/infinispan/templates/infinispan-ephemeral.json
  community/infinispan/templates/infinispan-persistent.json
  community/nodejs/imagestreams/nodejs-centos7.json
Labels: approved, lgtm, size/XL
