Repository openshift/library, pull requests merged in 2018-06, with the labels that each got.

#90 Update Fuse entries with 7.0 release
  official.yaml
  official/README.md
  official/fis/templates/fuse70-console.json
  official/fis/templates/s2i-spring-boot-camel-xml.json
  official/fis/templates/s2i-spring-boot-camel.json
  official/index.json
Labels: size/XXL

#91 bumping the 3scale apicast version
  official.yaml
  official/3scale/imagestreams/apicast-gateway.json
  official/3scale/templates/3scale-gateway.json
  official/README.md
  official/index.json
Labels: size/M

#93 CLOUD-2593 - Deprecate AMQ 6.2
  official.yaml
  official/README.md
  official/amq/templates/amq62-basic.json
  official/amq/templates/amq62-persistent-ssl.json
  official/amq/templates/amq62-persistent.json
  official/amq/templates/amq62-ssl.json
  official/index.json
Labels: size/XXL

#97 Introduces Apicast Secrets to the template
  official/3scale/templates/3scale-gateway.json
Labels: size/S

#95 update for latest Java S2I image and templates
  official.yaml
  official/README.md
  official/index.json
  official/java/imagestreams/java-rhel7.json
  official/java/imagestreams/redhat-openjdk18-openshift-rhel7.json
  official/java/templates/openjdk18-web-basic-s2i.json
Labels: size/L

#96 CLOUD-2683 Add Data Grid 7.2
  official.yaml
  official/README.md
  official/datagrid/imagestreams/jboss-datagrid72-openshift-rhel7.json
  official/datagrid/templates/datagrid72-basic.json
  official/datagrid/templates/datagrid72-https.json
  official/datagrid/templates/datagrid72-mysql-persistent.json
  official/datagrid/templates/datagrid72-mysql.json
  official/datagrid/templates/datagrid72-postgresql-persistent.json
  official/datagrid/templates/datagrid72-postgresql.json
  official/index.json
Labels: size/XXL
