Repository openshift/library, pull requests merged in 2019-04, with the labels that each got.

#160 4.1 Code Freeze
  README.md
Labels: approved, lgtm, size/XS

#161 chore: add a React Web Example using the Web App builder image
  official.yaml
  official/README.md
  official/index.json
  official/modern-webapp/imagestreams/modern-webapp-rhel7.json
  official/modern-webapp/templates/react-web-app-example.json
Labels: approved, lgtm, ok-to-test, size/L

#162 Bump version to 1.4.18 for jboss-amq
  official.yaml
  official/README.md
  official/amq/imagestreams/jboss-amq-62-rhel7.json
  official/amq/imagestreams/jboss-amq-63-rhel7.json
  official/amq/templates/amq63-basic.json
  official/amq/templates/amq63-persistent-ssl.json
  official/amq/templates/amq63-persistent.json
  official/amq/templates/amq63-ssl.json
  official/index.json
Labels: approved, lgtm, size/L

#163 revert #162
  official.yaml
  official/README.md
  official/amq/imagestreams/jboss-amq-62-rhel7.json
  official/amq/imagestreams/jboss-amq-63-rhel7.json
  official/amq/templates/amq63-basic.json
  official/amq/templates/amq63-persistent-ssl.json
  official/amq/templates/amq63-persistent.json
  official/amq/templates/amq63-ssl.json
  official/index.json
Labels: approved, lgtm, size/L

#166 Pointed to new openjdk location and updated xpaas version
  official.yaml
  official/README.md
  official/index.json
  official/java/imagestreams/java-rhel7.json
  official/java/imagestreams/openjdk-11-rhel7-rhel7.json
  official/java/imagestreams/redhat-openjdk18-openshift-rhel7.json
  official/java/templates/openjdk-web-basic-s2i.json
  official/sso/imagestreams/redhat-sso-cd-openshift-rhel7.json
  official/sso/templates/sso-cd-x509-https.json
Labels: approved, lgtm, size/L
