Repository openshift/library, pull requests merged in 2019-05, with the labels that each got.

#168 Update Fuse entries with 7.3 release
  official.yaml
  official/README.md
  official/fis/templates/s2i-fuse73-spring-boot-camel-rest-3scale.json
  official/index.json
Labels: approved, lgtm, size/L

#169 [KIECLOUD-214] - Update RHDM and RHPAM 7.3.1 templates on OCP and OSO…
  official.yaml
  official/README.md
  official/index.json
  official/rhdm/imagestreams/rhdm73-decisioncentral-indexing-openshift-rhel7.json
  official/rhdm/imagestreams/rhdm73-decisioncentral-openshift-rhel7.json
  official/rhdm/imagestreams/rhdm73-kieserver-openshift-rhel7.json
  official/rhdm/imagestreams/rhdm73-optaweb-employee-rostering-openshift-rhel7.json
  official/rhdm/templates/rhdm73-authoring-ha.json
  official/rhdm/templates/rhdm73-authoring.json
  official/rhdm/templates/rhdm73-kieserver.json
  official/rhdm/templates/rhdm73-optaweb-employee-rostering.json
  official/rhdm/templates/rhdm73-prod-immutable-kieserver.json
  official/rhdm/templates/rhdm73-trial-ephemeral.json
  official/rhpam/imagestreams/rhpam73-businesscentral-indexing-openshift-rhel7.json
  official/rhpam/imagestreams/rhpam73-businesscentral-monitoring-openshift-rhel7.json
  official/rhpam/imagestreams/rhpam73-businesscentral-openshift-rhel7.json
  official/rhpam/imagestreams/rhpam73-kieserver-openshift-rhel7.json
  official/rhpam/imagestreams/rhpam73-smartrouter-openshift-rhel7.json
  official/rhpam/templates/rhpam73-authoring-ha.json
  official/rhpam/templates/rhpam73-authoring.json
  official/rhpam/templates/rhpam73-kieserver-externaldb.json
  official/rhpam/templates/rhpam73-kieserver-mysql.json
  official/rhpam/templates/rhpam73-kieserver-postgresql.json
  official/rhpam/templates/rhpam73-managed.json
  official/rhpam/templates/rhpam73-prod-immutable-kieserver.json
  official/rhpam/templates/rhpam73-prod-immutable-monitor.json
  official/rhpam/templates/rhpam73-prod.json
  official/rhpam/templates/rhpam73-trial-ephemeral.json
Labels: approved, lgtm, ok-to-test, size/XXL

#170 Add GoLang CentOS builder image-stream
  community.yaml
  community/README.md
  community/golang/imagestreams/golang-centos7.json
  community/index.json
Labels: approved, lgtm, size/M

#173 Add Dockerfile for ci-operator
  Dockerfile
Labels: approved, lgtm, size/XS

#171 Restore AMQ bump
  README.md
  official.yaml
  official/README.md
  official/amq/imagestreams/jboss-amq-62-rhel7.json
  official/amq/imagestreams/jboss-amq-63-rhel7.json
  official/amq/templates/amq63-basic.json
  official/amq/templates/amq63-persistent-ssl.json
  official/amq/templates/amq63-persistent.json
  official/amq/templates/amq63-ssl.json
  official/index.json
Labels: approved, lgtm, size/L

#174 Added golang rhel7 imagestream
  official.yaml
  official/README.md
  official/golang/imagestreams/golang-rhel7.json
  official/index.json
Labels: approved, lgtm, size/M
