Repository openshift/library, pull requests merged in 2019-09, with the labels that each got.

#188 update verify image so it can perform samples importing+pushing
  Dockerfile
Labels: approved, lgtm, size/XS

#190 remove lone ppc piece of content
  official.yaml
  official/README.md
  official/index.json
  official/ruby/imagestreams/ruby-rhel7.json
Labels: approved, lgtm, size/M

#189 Add Open Liberty imagestream to official imagestreams
  community.yaml
  community/README.md
  community/index.json
  community/openliberty/imagestreams/openliberty.json
  official.yaml
Labels: approved, lgtm, ok-to-test, size/M

#191 Add templates for Monitored Jenkins
  arch/x86_64/official/jenkins/templates/jenkins-ephemeral-monitored.json
  arch/x86_64/official/jenkins/templates/jenkins-persistent-monitored.json
  official.yaml
  official/README.md
  official/index.json
  official/jenkins/templates/jenkins-ephemeral-monitored.json
  official/jenkins/templates/jenkins-persistent-monitored.json
  online/professional/x86_64/official/jenkins/templates/jenkins-ephemeral-monitored.json
  online/professional/x86_64/official/jenkins/templates/jenkins-persistent-monitored.json
  online/starter/x86_64/official/jenkins/templates/jenkins-ephemeral-monitored.json
  online/starter/x86_64/official/jenkins/templates/jenkins-persistent-monitored.json
  operator/ocp-x86_64/official/jenkins/templates/jenkins-ephemeral-monitored.json
  operator/ocp-x86_64/official/jenkins/templates/jenkins-persistent-monitored.json
  operator/okd-x86_64/official/jenkins/templates/jenkins-ephemeral-monitored.json
  operator/okd-x86_64/official/jenkins/templates/jenkins-persistent-monitored.json
Labels: approved, lgtm, size/XXL
