Repository openshift/library, pull requests merged in 2019-02, with the labels that each got.

#146 Update to EAP CD 15
  official.yaml
  official/README.md
  official/eap-cd/imagestreams/eap-cd-openshift-rhel7.json
  official/eap-cd/templates/eap-cd-basic-s2i.json
  official/eap-cd/templates/eap-cd-postgresql-persistent-s2i.json
  official/eap-cd/templates/eap-cd-starter-s2i.json
  official/index.json
Labels: approved, lgtm, needs-ok-to-test, size/M

#147 [KIECLOUD-112] - Update RHPAM/DM templates on OpenShift Service Catal…
  community/php/imagestreams/php-centos7.json
  official.yaml
  official/README.md
  official/index.json
  official/php/imagestreams/php-rhel7.json
  official/rhdm/imagestreams/rhdm72-decisioncentral-indexing-openshift-rhel7.json
  official/rhdm/imagestreams/rhdm72-decisioncentral-openshift-rhel7.json
  official/rhdm/imagestreams/rhdm72-kieserver-openshift-rhel7.json
  official/rhdm/imagestreams/rhdm72-optaweb-employee-rostering-openshift-rhel7.json
  official/rhdm/templates/rhdm72-authoring-ha.json
  official/rhdm/templates/rhdm72-authoring.json
  official/rhdm/templates/rhdm72-kieserver.json
  official/rhdm/templates/rhdm72-optaweb-employee-rostering-trial-ephemeral.json
  official/rhdm/templates/rhdm72-prod-immutable-kieserver.json
  official/rhdm/templates/rhdm72-trial-ephemeral.json
  official/rhpam/imagestreams/rhpam72-businesscentral-indexing-openshift-rhel7.json
  official/rhpam/imagestreams/rhpam72-businesscentral-monitoring-openshift-rhel7.json
  official/rhpam/imagestreams/rhpam72-businesscentral-openshift-rhel7.json
  official/rhpam/imagestreams/rhpam72-kieserver-openshift-rhel7.json
  official/rhpam/imagestreams/rhpam72-smartrouter-openshift-rhel7.json
  official/rhpam/templates/rhpam72-authoring-ha.json
  official/rhpam/templates/rhpam72-authoring.json
  official/rhpam/templates/rhpam72-kieserver-externaldb.json
  official/rhpam/templates/rhpam72-kieserver-mysql.json
  official/rhpam/templates/rhpam72-kieserver-postgresql.json
  official/rhpam/templates/rhpam72-prod-immutable-kieserver.json
  official/rhpam/templates/rhpam72-prod-immutable-monitor.json
  official/rhpam/templates/rhpam72-prod.json
  official/rhpam/templates/rhpam72-trial-ephemeral.json
Labels: approved, lgtm, needs-ok-to-test, size/XL

#149 add pweil- as approver
  OWNERS
Labels: size/XS

#148 Add Nginx/Apache (httpd) to Starter/Pro
  official.yaml
Labels: approved, lgtm, size/XS

#150 add more folks to approver list
  OWNERS
Labels: approved, lgtm, size/XS

#152 Update EAP 7.1 & 6.4 OpenShift imagestreams and templates to ose-v1.4.18
  official.yaml
  official/README.md
  official/eap/imagestreams/jboss-eap64-openshift-rhel7.json
  official/eap/imagestreams/jboss-eap70-openshift-rhel7.json
  official/eap/imagestreams/jboss-eap71-openshift-rhel7.json
  official/eap/templates/eap64-amq-persistent-s2i.json
  official/eap/templates/eap64-amq-s2i.json
  official/eap/templates/eap64-basic-s2i.json
  official/eap/templates/eap64-https-s2i.json
  official/eap/templates/eap64-mongodb-persistent-s2i.json
  official/eap/templates/eap64-mongodb-s2i.json
  official/eap/templates/eap64-mysql-persistent-s2i.json
  official/eap/templates/eap64-mysql-s2i.json
  official/eap/templates/eap64-postgresql-persistent-s2i.json
  official/eap/templates/eap64-postgresql-s2i.json
  official/eap/templates/eap64-sso-s2i.json
  official/eap/templates/eap64-third-party-db-s2i.json
  official/eap/templates/eap64-tx-recovery-s2i.json
  official/eap/templates/eap71-amq-persistent-s2i.json
  official/eap/templates/eap71-amq-s2i.json
  official/eap/templates/eap71-basic-s2i.json
  official/eap/templates/eap71-https-s2i.json
  official/eap/templates/eap71-mongodb-persistent-s2i.json
  official/eap/templates/eap71-mongodb-s2i.json
  official/eap/templates/eap71-mysql-persistent-s2i.json
  official/eap/templates/eap71-mysql-s2i.json
  official/eap/templates/eap71-postgresql-persistent-s2i.json
  official/eap/templates/eap71-postgresql-s2i.json
  official/eap/templates/eap71-sso-s2i.json
  official/eap/templates/eap71-third-party-db-s2i.json
  official/eap/templates/eap71-tx-recovery-s2i.json
  official/index.json
Labels: approved, lgtm, ok-to-test, size/L

#153 JDG-2121 JDG-2258 Remove deprecated templates, add datagrid service
  official.yaml
  official/README.md
  official/datagrid/imagestreams/jboss-datagrid72-openshift-rhel7.json
  official/datagrid/templates/cache-service.json
  official/datagrid/templates/datagrid-service.json
  official/datagrid/templates/datagrid65-basic.json
  official/datagrid/templates/datagrid65-https.json
  official/datagrid/templates/datagrid65-mysql-persistent.json
  official/datagrid/templates/datagrid65-mysql.json
  official/datagrid/templates/datagrid65-postgresql-persistent.json
  official/datagrid/templates/datagrid65-postgresql.json
  official/datagrid/templates/datagrid71-basic.json
  official/datagrid/templates/datagrid71-https.json
  official/datagrid/templates/datagrid71-mysql-persistent.json
  official/datagrid/templates/datagrid71-mysql.json
  official/datagrid/templates/datagrid71-postgresql-persistent.json
  official/datagrid/templates/datagrid71-postgresql.json
  official/datagrid/templates/datagrid72-basic.json
  official/datagrid/templates/datagrid72-https.json
  official/datagrid/templates/datagrid72-mysql-persistent.json
  official/datagrid/templates/datagrid72-mysql.json
  official/datagrid/templates/datagrid72-postgresql-persistent.json
  official/datagrid/templates/datagrid72-postgresql.json
  official/index.json
Labels: approved, lgtm, ok-to-test, size/XXL
