Repository openshift/library, pull requests merged in 2019-01, with the labels that each got.

#142 [KIECLOUD-71] - Update PAM and DM templates on OpenShift for 7.2.0
  official.yaml
  official/README.md
  official/index.json
  official/rhdm/imagestreams/rhdm71-decisioncentral-indexing-openshift-rhel7.json
  official/rhdm/imagestreams/rhdm71-decisioncentral-openshift-rhel7.json
  official/rhdm/imagestreams/rhdm71-kieserver-openshift-rhel7.json
  official/rhdm/imagestreams/rhdm71-optaweb-employee-rostering-openshift-rhel7.json
  official/rhdm/imagestreams/rhdm72-decisioncentral-indexing-openshift-rhel7.json
  official/rhdm/imagestreams/rhdm72-decisioncentral-openshift-rhel7.json
  official/rhdm/imagestreams/rhdm72-kieserver-openshift-rhel7.json
  official/rhdm/imagestreams/rhdm72-optaweb-employee-rostering-openshift-rhel7.json
  official/rhdm/templates/rhdm72-authoring-ha.json
  official/rhdm/templates/rhdm72-authoring.json
  official/rhdm/templates/rhdm72-kieserver.json
  official/rhdm/templates/rhdm72-optaweb-employee-rostering-trial-ephemeral.json
  official/rhdm/templates/rhdm72-prod-immutable-kieserver.json
  official/rhdm/templates/rhdm72-trial-ephemeral.json
  official/rhpam/imagestreams/rhpam71-businesscentral-indexing-openshift-rhel7.json
  official/rhpam/imagestreams/rhpam71-businesscentral-monitoring-openshift-rhel7.json
  official/rhpam/imagestreams/rhpam71-businesscentral-openshift-rhel7.json
  official/rhpam/imagestreams/rhpam71-kieserver-openshift-rhel7.json
  official/rhpam/imagestreams/rhpam71-smartrouter-openshift-rhel7.json
  official/rhpam/imagestreams/rhpam72-businesscentral-indexing-openshift-rhel7.json
  official/rhpam/imagestreams/rhpam72-businesscentral-monitoring-openshift-rhel7.json
  official/rhpam/imagestreams/rhpam72-businesscentral-openshift-rhel7.json
  official/rhpam/imagestreams/rhpam72-kieserver-openshift-rhel7.json
  official/rhpam/imagestreams/rhpam72-smartrouter-openshift-rhel7.json
  official/rhpam/templates/rhpam71-prod.json
  official/rhpam/templates/rhpam72-authoring-ha.json
  official/rhpam/templates/rhpam72-authoring.json
  official/rhpam/templates/rhpam72-kieserver-externaldb.json
  official/rhpam/templates/rhpam72-kieserver-mysql.json
  official/rhpam/templates/rhpam72-kieserver-postgresql.json
  official/rhpam/templates/rhpam72-prod-immutable-kieserver.json
  official/rhpam/templates/rhpam72-prod-immutable-monitor.json
  official/rhpam/templates/rhpam72-prod.json
  official/rhpam/templates/rhpam72-trial-ephemeral.json
Labels: approved, lgtm, ok-to-test, size/XXL

#144 update EAP 7.2 SSO template to use the correct SSO 7.3 adapters
  official/eap/templates/eap72-sso-s2i.json
Labels: approved, lgtm, ok-to-test, size/XS

#145 add jenkins agent imagestreams
  community.yaml
  community/README.md
  community/index.json
  community/jenkins/imagestreams/jenkins-agent-maven-centos7.json
  community/jenkins/imagestreams/jenkins-agent-nodejs-centos7.json
  official.yaml
  official/README.md
  official/index.json
  official/jenkins/imagestreams/jenkins-agent-maven-rhel7.json
  official/jenkins/imagestreams/jenkins-agent-nodejs-rhel7.json
  operator/ocp-x86_64/official/README.md
  operator/ocp-x86_64/official/index.json
  operator/ocp-x86_64/official/jenkins/imagestreams/jenkins-agent-maven-rhel7.json
  operator/ocp-x86_64/official/jenkins/imagestreams/jenkins-agent-nodejs-rhel7.json
  operator/okd-x86_64/community/README.md
  operator/okd-x86_64/community/index.json
  operator/okd-x86_64/community/jenkins/imagestreams/jenkins-agent-maven-centos7.json
  operator/okd-x86_64/community/jenkins/imagestreams/jenkins-agent-nodejs-centos7.json
Labels: approved, lgtm, size/L
