Repository openshift/library, pull requests merged in 2020-01, with the labels that each got.

#200 fix nodejs scl repo for community as well
  community.yaml
  community/README.md
  community/index.json
  community/nodejs/imagestreams/nodejs-centos7.json
Labels: approved, lgtm, size/M

#202 Update Datagrid Version to 7.3-v1.4
  official.yaml
  official/README.md
  official/datagrid/imagestreams/jboss-datagrid73-openshift-rhel7.json
  official/datagrid/templates/cache-service.json
  official/datagrid/templates/datagrid-service.json
  official/index.json
Labels: approved, lgtm, ok-to-test, size/M

#201 add s390 and ppc imagestream defs for mariadb
  official.yaml
  official/README.md
  official/index.json
  official/mariadb/imagestreams/mariadb-rhel7-ppc64le.json
  official/mariadb/imagestreams/mariadb-rhel7-s390x.json
Labels: approved, lgtm, size/L

#204 Update EAP CD to 18 / RHEL 8 on OCP 4
  official.yaml
  official/README.md
  official/eap-cd/imagestreams/eap-cd-openshift-rhel8.json
  official/eap-cd/imagestreams/eap-cd-runtime-openshift-rhel8.json
  official/eap-cd/templates/eap-cd-basic-s2i.json
  official/eap-cd/templates/eap-cd-starter-s2i.json
  official/index.json
Labels: approved, lgtm, ok-to-test, size/L
