Repository openshift/library, pull requests merged in 2021-08, with the labels that each got.

#283 [KIECLOUD-568] - Update RHPAM and RHDM templates and imagestreams on …
  official.yaml
  official/rhdm/imagestreams/rhdm-decisioncentral-rhel8.json
  official/rhdm/imagestreams/rhdm-kieserver-rhel8.json
  official/rhdm/templates/rhdm711-authoring-ha.json
  official/rhdm/templates/rhdm711-authoring.json
  official/rhdm/templates/rhdm711-kieserver.json
  official/rhdm/templates/rhdm711-prod-immutable-kieserver-amq.json
  official/rhdm/templates/rhdm711-prod-immutable-kieserver.json
  official/rhdm/templates/rhdm711-trial-ephemeral.json
  official/rhpam/imagestreams/rhpam-businesscentral-monitoring-rhel8.json
  official/rhpam/imagestreams/rhpam-businesscentral-rhel8.json
  official/rhpam/imagestreams/rhpam-kieserver-rhel8.json
  official/rhpam/imagestreams/rhpam-smartrouter-rhel8.json
  official/rhpam/templates/rhpam711-authoring-ha.json
  official/rhpam/templates/rhpam711-authoring.json
  official/rhpam/templates/rhpam711-kieserver-externaldb.json
  official/rhpam/templates/rhpam711-kieserver-mysql.json
  official/rhpam/templates/rhpam711-kieserver-postgresql.json
  official/rhpam/templates/rhpam711-managed.json
  official/rhpam/templates/rhpam711-prod-immutable-kieserver-amq.json
  official/rhpam/templates/rhpam711-prod-immutable-kieserver.json
  official/rhpam/templates/rhpam711-prod-immutable-monitor.json
  official/rhpam/templates/rhpam711-prod.json
  official/rhpam/templates/rhpam711-trial-ephemeral.json
Labels: approved, lgtm, needs-ok-to-test

#284 [KEYCLOAK-17987] Update RH-SSO templates & imagestreams to the latest…
  official.yaml
  official/sso/imagestreams/sso74-openj9-openshift-rhel8.json
  official/sso/imagestreams/sso74-openshift-rhel8.json
  official/sso/templates/sso74-https.json
  official/sso/templates/sso74-ocp4-x509-https.json
  official/sso/templates/sso74-ocp4-x509-postgresql-persistent.json
  official/sso/templates/sso74-openj9-https.json
  official/sso/templates/sso74-openj9-ocp4-x509-https.json
  official/sso/templates/sso74-openj9-ocp4-x509-postgresql-persistent.json
  official/sso/templates/sso74-openj9-postgresql-persistent.json
  official/sso/templates/sso74-openj9-postgresql.json
  official/sso/templates/sso74-postgresql-persistent.json
  official/sso/templates/sso74-postgresql.json
Labels: approved, lgtm, needs-ok-to-test

#285 Update OWNERS
  OWNERS
Labels: approved, lgtm

#286 Update EAP templates, add EAP XP 3
  official.yaml
  official/eap-cd/imagestreams/eap-cd-openshift-rhel8.json
  official/eap-cd/imagestreams/eap-cd-runtime-openshift-rhel8.json
  official/eap-cd/templates/eap-cd-basic-s2i.json
  official/eap-cd/templates/eap-cd-starter-s2i.json
  official/eap/imagestreams/jboss-eap-xp3-openjdk11-openshift-rhel8.json
  official/eap/imagestreams/jboss-eap-xp3-openjdk11-runtime-openshift-rhel8.json
  official/eap/templates/eap-xp3-basic-s2i.json
  official/eap/templates/eap64-amq-persistent-s2i.json
  official/eap/templates/eap64-amq-s2i.json
  official/eap/templates/eap64-basic-s2i.json
  official/eap/templates/eap64-https-s2i.json
  official/eap/templates/eap64-mongodb-persistent-s2i.json
  official/eap/templates/eap64-mongodb-s2i.json
  official/eap/templates/eap64-mysql-persistent-s2i.json
  official/eap/templates/eap64-mysql-s2i.json
  official/eap/templates/eap64-postgresql-persistent-s2i.json
  official/eap/templates/eap64-postgresql-s2i.json
  official/eap/templates/eap64-sso-s2i.json
  official/eap/templates/eap64-third-party-db-s2i.json
  official/eap/templates/eap64-tx-recovery-s2i.json
  official/eap/templates/eap73-basic-s2i.json
  official/eap/templates/eap73-sso-s2i.json
  official/eap/templates/eap73-third-party-db-s2i.json
Labels: approved, lgtm, ok-to-test
